### ISSUE TITLE
Super monkey paragon wayyyy too weak

### ISSUE THREAD

**Issue by Paccetine** [Jonyboylovespie/MagicParagons#1]
it took 7 seconds to kill a round 100 bad at degree 100 it is pathetic for the price

**Comment by Jonyboylovespie** [comment]
It literally makes u invincible lmao

**Comment by Paccetine** [comment]
oh
what

**Comment by Paccetine** [comment]
i change my mind nerf it

**Comment by Jonyboylovespie** [comment]
Omg bro stop fucking complaining

**Comment by Paccetine** [comment]
dam chill
it was a joke
